-- ============================================================================
-- SANTOS.TRAVEL — IVA Cortex Database Schema
-- Phase 1: Data Foundation
-- Strict separation: static vendor inventory vs dynamic client data
-- ============================================================================

-- ---------------------------------------------------------------------------
-- ENUMS
-- ---------------------------------------------------------------------------
CREATE TYPE vendor_type AS ENUM ('hotel', 'transport', 'guide', 'activity', 'meals', 'misc');
CREATE TYPE product_category AS ENUM (
  'accommodation', 'transfer', 'sightseeing', 'guide', 'meals', 'activity', 'misc'
);
CREATE TYPE pricing_unit AS ENUM ('per_room', 'per_person', 'per_vehicle', 'per_trip');
CREATE TYPE lead_source AS ENUM ('whatsapp', 'email', 'web', 'voice', 'api', 'manual');
CREATE TYPE inquiry_status AS ENUM ('new', 'triaged', 'quoting', 'quoted', 'converted', 'lost');
CREATE TYPE quote_status AS ENUM ('draft', 'sent', 'accepted', 'rejected', 'expired');
CREATE TYPE trip_status AS ENUM ('upcoming', 'ongoing', 'completed', 'cancelled');
CREATE TYPE event_type AS ENUM ('pickup', 'dropoff', 'sightseeing', 'meal', 'guide', 'activity', 'transfer');
CREATE TYPE event_status AS ENUM ('pending', 'confirmed', 'in_progress', 'completed', 'missed');

-- ---------------------------------------------------------------------------
-- STATIC VENDOR INVENTORY (read by quoting engine, never mutated by AI)
-- ---------------------------------------------------------------------------
CREATE TABLE vendors (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name          VARCHAR(255) NOT NULL,
  type          vendor_type NOT NULL,
  contact_name  VARCHAR(255),
  contact_phone VARCHAR(50),
  contact_email VARCHAR(255),
  commission_pct NUMERIC(5,2) NOT NULL DEFAULT 0,
  payment_terms TEXT,
  is_active    BOOLEAN NOT NULL DEFAULT true,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE vendor_products (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  vendor_id     UUID NOT NULL REFERENCES vendors(id),
  name          VARCHAR(255) NOT NULL,
  category      product_category NOT NULL,
  description   TEXT,
  base_price    NUMERIC(12,2) NOT NULL,
  currency      VARCHAR(3) NOT NULL DEFAULT 'INR',
  pricing_unit  pricing_unit NOT NULL DEFAULT 'per_person',
  valid_from    DATE NOT NULL,
  valid_until   DATE NOT NULL,
  is_active     BOOLEAN NOT NULL DEFAULT true,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT valid_dates CHECK (valid_until > valid_from)
);

CREATE INDEX idx_vendor_products_vendor ON vendor_products(vendor_id);
CREATE INDEX idx_vendor_products_category ON vendor_products(category);
CREATE INDEX idx_vendor_products_active_dates ON vendor_products(is_active, valid_from, valid_until);

-- ---------------------------------------------------------------------------
-- DYNAMIC CLIENT DATA (written by intake, read/written by quoting engine)
-- ---------------------------------------------------------------------------
CREATE TABLE inquiries (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  source        lead_source NOT NULL,
  raw_message   TEXT,
  extracted_data JSONB,
  status        inquiry_status NOT NULL DEFAULT 'new',
  pax_adults    INT,
  pax_children  INT DEFAULT 0,
  check_in      DATE,
  check_out     DATE,
  destination   VARCHAR(255),
  budget_range  JSONB,
  lead_name     VARCHAR(255),
  lead_email    VARCHAR(255),
  lead_phone    VARCHAR(50),
  assigned_to   VARCHAR(255),
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_inquiries_status ON inquiries(status);
CREATE INDEX idx_inquiries_created ON inquiries(created_at DESC);
CREATE INDEX idx_inquiries_source ON inquiries(source);

-- ---------------------------------------------------------------------------
-- QUOTES (generated by deterministic engine; LLM only writes prose)
-- ---------------------------------------------------------------------------
CREATE TABLE quotes (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  inquiry_id      UUID NOT NULL REFERENCES inquiries(id),
  quote_number    VARCHAR(20) NOT NULL,
  status          quote_status NOT NULL DEFAULT 'draft',
  total_cost      NUMERIC(12,2) NOT NULL DEFAULT 0,
  total_margin    NUMERIC(12,2) NOT NULL DEFAULT 0,
  grand_total     NUMERIC(12,2) NOT NULL DEFAULT 0,
  markup_pct      NUMERIC(5,2) NOT NULL DEFAULT 0,
  currency        VARCHAR(3) NOT NULL DEFAULT 'INR',
  valid_until     DATE,
  terms_conditions TEXT,
  llm_prose       TEXT,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT unique_quote_number UNIQUE (quote_number)
);

CREATE INDEX idx_quotes_inquiry ON quotes(inquiry_id);
CREATE INDEX idx_quotes_status ON quotes(status);

CREATE TABLE quote_line_items (
  id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  quote_id          UUID NOT NULL REFERENCES quotes(id) ON DELETE CASCADE,
  vendor_product_id UUID REFERENCES vendor_products(id),
  description       TEXT NOT NULL,
  quantity          INT NOT NULL DEFAULT 1,
  unit_cost         NUMERIC(12,2) NOT NULL DEFAULT 0,
  unit_margin       NUMERIC(12,2) NOT NULL DEFAULT 0,
  unit_selling      NUMERIC(12,2) NOT NULL DEFAULT 0,
  total             NUMERIC(12,2) NOT NULL DEFAULT 0,
  sort_order        INT NOT NULL DEFAULT 0,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT positive_quantity CHECK (quantity > 0)
);

CREATE INDEX idx_line_items_quote ON quote_line_items(quote_id);

-- ---------------------------------------------------------------------------
-- TRIPS & EVENTS (Phase 4 — scaffolded here for FK integrity)
-- ---------------------------------------------------------------------------
CREATE TABLE trips (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  quote_id        UUID NOT NULL REFERENCES quotes(id),
  status          trip_status NOT NULL DEFAULT 'upcoming',
  start_date      DATE,
  end_date        DATE,
  lead_traveler   VARCHAR(255),
  lead_phone      VARCHAR(50),
  emergency_contact JSONB,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_trips_status ON trips(status);

CREATE TABLE trip_events (
  id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  trip_id           UUID NOT NULL REFERENCES trips(id) ON DELETE CASCADE,
  vendor_product_id UUID REFERENCES vendor_products(id),
  event_type        event_type NOT NULL,
  scheduled_at      TIMESTAMPTZ NOT NULL,
  duration_minutes  INT,
  location          VARCHAR(255),
  notes             TEXT,
  status            event_status NOT NULL DEFAULT 'pending',
  created_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_trip_events_trip ON trip_events(trip_id);
CREATE INDEX idx_trip_events_scheduled ON trip_events(scheduled_at);

-- ---------------------------------------------------------------------------
-- AUTO-UPDATE updated_at TRIGGER
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION trigger_set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER set_updated_at_vendors       BEFORE UPDATE ON vendors       FOR EACH ROW EXECUTE FUNCTION trigger_set_updated_at();
CREATE TRIGGER set_updated_at_vendor_products BEFORE UPDATE ON vendor_products FOR EACH ROW EXECUTE FUNCTION trigger_set_updated_at();
CREATE TRIGGER set_updated_at_inquiries     BEFORE UPDATE ON inquiries     FOR EACH ROW EXECUTE FUNCTION trigger_set_updated_at();
CREATE TRIGGER set_updated_at_quotes        BEFORE UPDATE ON quotes        FOR EACH ROW EXECUTE FUNCTION trigger_set_updated_at();
CREATE TRIGGER set_updated_at_trips         BEFORE UPDATE ON trips         FOR EACH ROW EXECUTE FUNCTION trigger_set_updated_at();
